### ISSUE TITLE
config.yaml; DEBUG: false gives Bad Request (400)

### ISSUE THREAD

**Issue by sheijmans** [propyless/panopuppet#106]
When setting the DEBUG option from true to false, the URL gives a; Bad Request (400)
Setting debug back to true, it works again.

Any idea what this could be?

**Comment by propyless** [comment]
Hello @sheijmans have you configured the following in the config.yaml?
 ```
ALLOWED_HOSTS:
  - '*' <-- or to whatever host you want
```

**Comment by sheijmans** [comment]
Hi @propyless,

No I didn't, I had the following as I was running firefox on the localhost.;
```
ALLOWED_HOSTS:
  - '127.0.0.1'
```
Setting it to;
```
ALLOWED_HOSTS:
- '*'
``` 
does fix it.

Setting it to a client IP  address, from which I access panopuppet,  it doesn't work (400).

**Comment by propyless** [comment]
Hmm that is strange. I will do some tests here with a client ip set and see if it works or not. Since it just uses the django internals it shouldn't be any panopuppet code that is breaking it.
Will get back with the results soon.

**Comment by propyless** [comment]
Ah I reread the documentation again. What the allowed_hosts does is only allow for certain hosts to reach the page.

So if my domain for pp is "pp.example.com"
then i can either add
ALLOWED_HOSTS = ["pp.example.com"]
this would not let us reach the page via "localhost" or "127.0.0.1"
If you want to reach the page via localhost or 127.0.0.1 you must add "localhost" and "127.0.0.1" to the list.
https://docs.djangoproject.com/en/1.9/ref/settings/#allowed-hosts

**Comment by sheijmans** [comment]
Aha, and `When DEBUG is True or when running tests, host validation is disabled;`

Tried to fixed it with;
```
ALLOWED_HOSTS:
  - ["localhost","127.0.0.1","puppet4.public.domain",".public.domain"]
```
but now it results in; Server Error (500)

**Comment by propyless** [comment]
Ah right, sorry I gave you python code directly.

But in config.yaml you will have to realize the list in yaml format.

```
ALLOWED_HOSTS:
  - 'localhost'
  - '127.0.0.1'
  - 'puppet4.public.domain'
  - '.public.domain'
```

Like above.

**Comment by sheijmans** [comment]
Nice one, this works, thnx.
