### ISSUE TITLE
TEMPLATE_DEBUG still needed?

### ISSUE THREAD

**Issue by sheijmans** [propyless/panopuppet#109]
Hi,

is TEMPLATE_DEBUG still needed in config.yaml(.example).
I read here [1][2] that it's deprecated since Django 1.8.

[1] https://docs.djangoproject.com/en/1.8/ref/settings/#template-debug
[2] http://docs.quantifiedcode.com/python-anti-patterns/django/1.8/migration/template_debug_deprecated.html

**Comment by propyless** [comment]
Does seem like it yes.. Thanks, i'll get on to fixing it!

**Comment by propyless** [comment]
As a relatively new django user I must admit I have not followed its development much, but you are indeed correct and this should be fixed. Will do this next release as well.

Thank you @sheijmans

**Comment by propyless** [comment]
PR #120 includes the update to the templates deprecated settings thing into the dev branch.

**Comment by propyless** [comment]
fix is in dev so will close this.
