### ISSUE TITLE
Update config file to use YAML instead of settings.py

### ISSUE THREAD

**Issue by nemski** [propyless/panopuppet#11]
The settings.py file should read from a YAML config file. Users with no knowledge of python should be able to install and use this system.

**Comment by propyless** [comment]
Its really super simple python. I'm not really sure what the problem is.

x = y
y = "hello world"
x = True

People edit lua config files and php config files all the time, whats so complicated with python?

**Comment by nemski** [comment]
The concept of data types should be abstracted away from a user. Think of a system administrator with no programming experience, should they really need to know how to define an array or null value in python? YAML is becoming the standard across all languages for config files because it provides a standard, so users don't need to understand how to write config files in lua, php, ruby and python.

**Comment by propyless** [comment]
Pull request available here: https://github.com/propyless/panopuppet/pull/14

**Comment by propyless** [comment]
Would you like to code review?

I was not really sure on how to structure hiera, but i think i kept it simple enough.
string, array and int.

**Comment by nemski** [comment]
Sorry I did read your code and forgot to review! I'm not much of a Python programmer but it looks OK to me.
