### ISSUE TITLE
Make compatible with PuppetDB 4.0

### ISSUE THREAD

**Issue by propyless** [propyless/panopuppet#119]
Perhaps investigate whether the new puppetdb query language should be used instead of the former.
Fix metric paths

**Comment by spicysomtam** [comment]
I would like this too. We have puppetboard for our 3.6.2 environment, but are looking to upgrade to 4.4. I have just built a new master and migrated our code across. Just setup puppetdb and need to find a dashboard. Puppetboard is fine, but you panopuppet looks good.

**Comment by propyless** [comment]
@spicysomtam Hey! Thanks! I'll make sure to prioritise this for you! :) Keep a look out in the near future and i'm sure it will be solved soon :)

**Comment by propyless** [comment]
added in #141

**Comment by spicysomtam** [comment]
Can you maybe paste in you config.yaml you used for puppet 4.4? I am struggling with this.

**Comment by propyless** [comment]
https://gist.github.com/propyless/a76c4a916659589ebd82108d371f5c69

This is an example config, its just a slightly cleaned up version of the example config found in the project root.

If you don't want file diff support through the client and filebucket you can set:
```
'PUPPETMASTER_CLIENTBUCKET_SHOW': false
'PUPPETMASTER_FILESERVER_SHOW': false
```
If you set the above to false. you can then remove these lines: https://gist.github.com/propyless/a76c4a916659589ebd82108d371f5c69#file-gistfile1-txt-L17-L29

Make sure to modify the rest of your settings to work with your installation paths etc.

**Comment by spicysomtam** [comment]
I have managed to get the v0.x pp to work with puppet 3.6.2/puppetdb 2.1. This is our existing environment. A good starting point is to get a simple config working (like your Staging example), and then once that works, move it up to a more complex config. With puppetdb 4, I think it only supports key based authentication; the port 8080/http access is no longer available, so this makes the setup much harder. We don't have this on 3.6.2. I'll enable the clientbucet and fileserver features on the v0.x when I have a bit of time. Thx for the quick response before.

**Comment by propyless** [comment]
Hello,

If you are using PE variant of PuppetDB I think you need to whitelist the servers that should have access to PuppetDB. If you are using FOSS, you just need to update the configuration for PuppetDB jetty for it to listen on 0.0.0.0 or the primary interface for the http (8080) port.

**Comment by propyless** [comment]
```
sources:
  'PuppetDB Production':
    'DEFAULT': true
    'PUPPETDB_HOST': 'http://puppetdb.production.example.com:8080/'
    'PUPPETDB_VERIFY_SSL': false
    
    'PUPPETMASTER_CLIENTBUCKET_SHOW': false
    'PUPPETMASTER_FILESERVER_SHOW': false    
    'PUPPET_RUN_INTERVAL': 30

# Time to hold the cache for pages - specified in seconds
CACHE_TIME: 60

#SQLITE_DIR: Where to write the sqliteDB used by panopuppet
SQLITE_DIR: '/var/www/panopuppet'

# Authentication method - Available auth methods = ldap and basic
AUTH_METHOD: 'basic'

ENABLE_PERMISSIONS: false

NODES_DEFAULT_FACTS:
  - 'os'
  - 'ipaddress'

########################
# DJANGO CONFIGURATION #
########################

# The session age is how long after the latest request the session cookie should expire.
# It is specified in hours - So the below would expire the cookie after two hours.
SESSION_AGE: 2


SECRET_KEY: 'super_secure_random_key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: false
TEMPLATE_DEBUG: false


#Allowed Hosts must be an array.
ALLOWED_HOSTS:
  - '*'
  
# Timezone settings for panopuppet. Catalog, report, fact times will be show localtime rather than GMT.
LANGUAGE_CODE: 'sv-SE'
TIME_ZONE: 'Europe/Stockholm'

# Where should the static files (js, css, etc) be stored?
STATIC_ROOT: '/srv/staticfiles' # default
```

The above is a really basic config that will use HTTP PuppetDB Port. It will also not use the Clientbucket and fileserver from the PuppetServer.

**Comment by sheijmans** [comment]
FYi,
just did a test upgrade of PuppetDB 3.2.4 to 4.1.0, didn't need to make any changes to PuppetDB config or Panopuppet (1.4.0) conf to get things working.

**Comment by propyless** [comment]
Yes the config for PanoPuppet used for PuppetDB 3.x <-> 4.x won't/shouldn't require any changes.

**Comment by spicysomtam** [comment]
Managed to get the puppetdb connection working with and without ssl. The default non ssl puppetdb is on port 8080; with later version of puppet this is not visible outside the puppet master, although you can configure it via jetty.ini. With ssl is 8081.

Without ssl:
```
'PUPPETDB_HOST': 'http://puppetdb.production.example.com:8080/'
'PUPPETDB_VERIFY_SSL': false
```

With ssl you need the ca authority cert and the pub/priv keys; I just stole these from the local host that was already signed to puppet:

```
    'PUPPETDB_HOST': 'https://puppetdb.production.example.com:8081/'
    'PUPPETDB_VERIFY_SSL': '/somewhere/panopuppet/certs/ca.pem'
    'PUPPETDB_CERTIFICATES':
      - '/somewhere/panopuppet/certs/hostname.pem'
      - '/somewhere/panopuppet/private_keys/hostname.pem'
```

**Comment by propyless** [comment]
Yep, thats all you gotta do.
Just a little more if you want Filebucket/Fileserver support =)

**Comment by spicysomtam** [comment]
Can I ask a question about V1.4: does it support puppetdb 2.1 and 4? I was kind of thinking it would be cool if you could have multiple databases defined (source:) and say one of them is puppetdb v4 and the other is v3 (or is it 2.1). Would that work or is it the case that 1.4 needs to use puppetdb 4?

**Comment by sheijmans** [comment]
As mentioned in the Support section of the README.md this will not work, v1.4 supports PuppetDB 3.x & 4.x

**Comment by spicysomtam** [comment]
Ah ok.

I managed to reinstall on my puppet master 4.5 today. All is working good.

Even managed to get the ldap authenication working against Active Directory and all the groups. A bit tricky this :) Think you could do with some docs on that.

Anyhow thx for panopuppet and all the help.

**Comment by sheijmans** [comment]
Hi @spicysomtam, good to hear that it is now working.

> Even managed to get the ldap authenication working against Active Directory and all the groups. A bit tricky this :) Think you could do with some docs on that. 

Perhaps you could help out with these docs, just edit this page;
https://github.com/propyless/panopuppet/wiki/LDAP-Configuration

**Comment by propyless** [comment]
Hi @spicysomtam! glad you got it working

LDAP is a bit of a pickle and especially since there are so many variants its hard to get a default that works for everyone. Some people have been forced to modify the settings.py for ldap configuration to get it working.

**Comment by spicysomtam** [comment]
Hi @sheijmans @propyless , thanks for the comments. I have added notes on the ldap config here: https://github.com/propyless/panopuppet/wiki/LDAP-Configuration. Feel free to correct anything. Hopefully it will be helpful as it was tricky. I was a bit of ldap guru at one point, so that helps.
