### ISSUE TITLE
Login returns error 500

### ISSUE THREAD

**Issue by nemski** [propyless/panopuppet#12]
Hi again,

I've configured panopuppet on Debian 7 with basic authentication (no LDAP) and no virtualenv. I created a root user but when I login I get an error 500. No logs in /var/log/apache2/panopuppet.error.log just this from access.log:

`x.x.1.211 - - [24/Apr/2015:14:59:32 +1000] "POST /pano/ HTTP/1.1" 500 300 "http://pano.syd.gsoa.ddau/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"`

**Comment by propyless** [comment]
did you pull the latest commit? 

https://github.com/propyless/panopuppet/blob/master/puppet/settings.py 
line 146 has been added. You are probably missing the LOGIN_URL. I would say,  git pull the latest commits and try again.

**Comment by propyless** [comment]
https://github.com/propyless/panopuppet/commit/941dc6b9f3f4f6352f4a39c6df723eb133a55644

**Comment by nemski** [comment]
I did a pull (that was painful, had to stash my changes and re-apply them). that didn't fix it. I turned on debug and was getting "read-only database" so I chowned db.sqlite3 as www-data:www-data. Now I'm getting "unable to open database file"

**Comment by propyless** [comment]
yes that pull is a painful one since you modify some lines in that file. but as you stated in that other issue, i could move those variables into config.yaml and pull those values from there instead.

Okay, have you initialized the database?
`python manage.py migrate

**Comment by nemski** [comment]
yep. I can try re-initializing, do I just blow it away and run that command again?

**Comment by propyless** [comment]
Yes I think thats all you need to do. I must admit that i've never really done this before so I can't say for sure.

**Comment by propyless** [comment]
I usually chown the panopuppet repository to www-data:www-data or in my case on rhel to apache:apache. But i'm not so certain if thats good security.

**Comment by nemski** [comment]
a `chown -R www-data:www-data /srv/repo/panopuppet` worked, but this is not good security.

**Comment by propyless** [comment]
I suppose I'll have to find out which permissions certain files will need to function properly.

**Comment by propyless** [comment]
closing issue but will fix the perms soon.
