### ISSUE TITLE
Facts Beautifier & Debian/jessie install instruction

### ISSUE THREAD

**Issue by ap-16** [propyless/panopuppet#123]
https://github.com/ap-16/panopuppet/tree/ap-16

**Comment by propyless** [comment]
Hey!

Thanks for the contribution. Initially the code looks good. I'll have to test it a little more when I get home so I can see how it looks. I'll open up a PR for you since you just created an issue to the "pr" content.

**Comment by propyless** [comment]
could you add a screenshot of the change to the facts just so i can see how it looks like? since i won't be home for a few hours..

**Comment by propyless** [comment]
Is present in DEV branch.
