### ISSUE TITLE
Catalogues: DataTables warning: table id=compare-with-table - Ajax error.

### ISSUE THREAD

**Issue by sheijmans** [propyless/panopuppet#128]
On one system I get the following error when providing a certname under Catalogues (using master branch);
DataTables warning: table id=compare-with-table - Ajax error. For more
information about this error, please see http://datatables.net/tn/7

Any idea what this can be?

**Comment by sheijmans** [comment]
Strange, couple of hours later, no changes made, now it work.
I'll take that.

**Comment by propyless** [comment]
Hi. Could your session have expired?

Mvh
Takeshi

**Comment by sheijmans** [comment]
Could be, I did not do a new login after some restarts of apache.

**Comment by propyless** [comment]
Yeah, thats probably the reason :) I need to fix some kind of redirect to the log in page when that happens.
