### ISSUE TITLE
Debian jessie problems with panopuppet version 1.3

### ISSUE THREAD

**Issue by ap-16** [propyless/panopuppet#138]
1/ More Debian packages are needed to be installed:
apt-get install python-setuptools
apt-get install pyconfigure
apt-get install python-dev
apt-get install libsasl2-dev

2/ Log reports an error:
 Target WSGI script '/opt/panopuppet/panopuppet/puppet/wsgi.py' cannot be loaded as Python module.
   File "/usr/lib/python3.4/posixpath.py", line 82, in join
     path = path + bb
 TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

Fixed in file /usr/lib/python3.4/posixpath.py line 76:

--- a/posixpath.py
+++ b/posixpath.py
@@ -73,7 +73,7 @@
     will be discarded.  An empty last part will result in a path that
     ends with a separator."""
     sep = _get_sep(a)
-    path = a
+    path = str( a )
     try:
         for b in p:
             if b.startswith(sep):

**Comment by propyless** [comment]
I don't think that theres an error with the posixpath.py, seems strange that that is the underlying cause.

Where do you have your config.py placed?

**Comment by ap-16** [comment]
It's absolut path is /etc/panopuppet/config.yaml

But /etc/apache2/sites-enabled/001-panopuppet.conf has contained some old config:
    WSGIDaemonProcess panopuppet user=www-data group=www-data threads=5 python-path=/opt/panopuppet:/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages

Changing this line to
    WSGIDaemonProcess panopuppet user=www-data group=www-data threads=5 python-path=/opt/panopuppet
calms this error.

**Comment by propyless** [comment]
Ah okay, excellent you fixed it!

Btw you can update the wiki with the packages you found are required.
https://github.com/propyless/panopuppet/wiki/Installation-Guides#debianjessie

**Comment by ap-16** [comment]
done!

BTW: Do you have a hint/link how to install the DB?

python3 /usr/local/lib/python2.7/dist-packages/Django-1.8.8-py2.7.egg/django/conf/project_template/manage.py 
says:
ImportError: No module named '{{ project_name }}'

Thank you

**Comment by propyless** [comment]
Aaaah.. I think the manage.py file in the repository is outdated! It should look a little more like:

Also I think that it can't locate ` os.environ.setdefault("DJANGO_SETTINGS_MODULE", "panopuppet.puppet.settings")`

So you need to make sure that panopuppet is in your python path.

```
#!/usr/bin/env python
import os
import sys

os.environ['PP_CFG'] = '/opt/rh/httpd24/root/var/www/pp.your.domain.com/config.yaml'

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "panopuppet.puppet.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)
```

**Comment by propyless** [comment]
Btw, you are welcome to join us at https://gitter.im/propyless/panopuppet =) (quicker reponse etc)

**Comment by ap-16** [comment]
thanks
