### ISSUE TITLE
RFE: change colors of the bars on the node report page

### ISSUE THREAD

**Issue by sheijmans** [propyless/panopuppet#139]
RFE for;
how about changing the colors of the bars on the node report page with the status of the puppet run;
changed/failed/noop/unchanged

**Comment by propyless** [comment]
![2016-05-25-193527_1427x761_scrot](https://cloud.githubusercontent.com/assets/6172961/15550047/e66adac4-22af-11e6-8ec4-0ce43976b38c.png)

How does this look?

**Comment by propyless** [comment]
![2016-05-25-204028_1408x846_scrot](https://cloud.githubusercontent.com/assets/6172961/15552041/05835b30-22b9-11e6-8d45-4d439c464e93.png)

**Comment by propyless** [comment]
![2016-05-25-204937_1431x1055_scrot](https://cloud.githubusercontent.com/assets/6172961/15552341/36fe1082-22ba-11e6-963f-504a350dd0fa.png)

**Comment by propyless** [comment]
![2016-05-25-211651_1514x1126_scrot](https://cloud.githubusercontent.com/assets/6172961/15553130/05aa98c6-22be-11e6-8b2a-c705a54a3497.png)

**Comment by propyless** [comment]
![2016-05-25-211819_1497x1226_scrot](https://cloud.githubusercontent.com/assets/6172961/15553181/4176d770-22be-11e6-88d1-14caffa7518d.png)

**Comment by sheijmans** [comment]
It looks very nice now, thanks.

**Comment by propyless** [comment]
![2016-05-26-175234_1513x743_scrot](https://cloud.githubusercontent.com/assets/6172961/15580902/b1121110-236a-11e6-94ea-8f0acad3c729.png)

Added a legend

**Comment by propyless** [comment]
Colors will be correct in the legend
