### ISSUE TITLE
Error  occurs with "Can not connect to PuppetDB" when click dashboard tag

### ISSUE THREAD

**Issue by zengxiaobai** [propyless/panopuppet#156]
Error  occurs with "Certname：Can not connect to PuppetDB" when click dashboard tag, but when I click the Nodes tag, everything is well。
when click dashboard, the puppetDB access log show response with status code :200 but httpd24 access log show response with status code 500.
I use PuppetDB5.0.1 and wonder if  beacause of the version?

follow is part of the splay:

click dashboard:
Certname | Latest Catalog | Latest Report | Latest Facts | Success | Noop | Failure | Skipped
-- | -- | -- | -- | -- | -- | -- | --
Can not connect to PuppetDB.

click Nodes: 
Certname | Catalog Timestamp | Report Timestamp | Facts Timestamp | Successes | Noops | Failures | Skipped
-- | -- | -- | -- | -- | -- | -- | --
panopuppet.xy.com | 2017-08-03 05:05:38 | 2017-08-03 05:05:38 | 2017-08-03 05:05:38 | 1 | 0 | 0 | 0

**Comment by propyless** [comment]
Hi @zengxiaobai, panopuppet is no longer maintained. So there is a high chance that it doesn't work anymore with the version of puppetdb you are using.

**Comment by zengxiaobai** [comment]
Thanks for your reply, I was sad to hear that because of much people recommend panopuppet. 
And I solved that problem just now. 
We should like to ask you which dashboard instead of panopupeet you are using now ? How about puppetboard? Thanks!

**Comment by sheijmans** [comment]
Puppetboard seems the way to go, actively maintained unlike puppetexplorer/panopuppet.
