### ISSUE TITLE
Sorting of columns on dashboard screen

### ISSUE THREAD

**Issue by fgimian** [propyless/panopuppet#18]
Hey there, really great job on PanoPuppet, we're currently trialing it for our puppet instance :smile: 

I was wondering if you could please add ability to sort by the columns in the dashboard page? (similar to the Nodes page)?

Also, are you interested in contributions?  I have some visual changes that I'd love to implement and propose for PanoPuppet.

Thanks
Fotis

**Comment by propyless** [comment]
I am interested in contributions. Just be aware that I don't have much ... any tests to make sure that the functionality in panopuppet does not break. What kind of visual implementations do you want?

I have been thinking about adding the ability to sort columns but I wasnt really sure if i wanted to implement it or not seeing as those pages are only really supposed to show the latest errors, changes, etc. But it wouldnt be all that difficult to for example implement the jquery filter plugin I am using on for example the events analytics pages and facts page.

**Comment by propyless** [comment]
Hello, take a look at the PR #19

**Comment by fgimian** [comment]
Thanks a lot, I'll test it out now and let you know :smile:

**Comment by fgimian** [comment]
I've just tried it out and it works great.  Though I'm not sure that the filtering is really needed for the dashboard, just the sorting would probably do, so it doesn't take so much room.

But yeah, this is very helpful for me personally :smile: 

Thanks so much for taking the time to consider and implement my idea
Fotis

**Comment by propyless** [comment]
Ah yes, thats true. I can create a new branch without the filtering if you are interested in testing just that out. :)

No thank you, the pleasures all mine. I'm glad there are people out there testing my dashboard. :)

What kind of visual ideas did you have for panopuppet?

**Comment by propyless** [comment]
I've added colspan to the columns and removed the filter bar. Do you want to check it out again before i merge it into master?

**Comment by propyless** [comment]
I've merged the PR. but ill keep this issue open a few more days so we can continue our discussion

**Comment by fgimian** [comment]
Hey there, sorry for the late reply, I'm checking it out now :smile:

**Comment by propyless** [comment]
I have checked out puppetboard, its the reason I wrote panopuppet =).
I have thought about changing the feel to the dashboard, but I am not sure how I want to do it yet. I do however agree that it should be clearer, today the numbers are quite small. Give me a couple of weeks to figure out how I want it to look?
Regarding the counts... I am unsure if I feel that counts should be to the left or not. I will ask around and see what other people think about it :) If the majority agrees I will swap things around.

I actually never saw that in the Events page and is not intended to look "old school"! Thanks for pointing that out :)

**Comment by fgimian** [comment]
Thanks for your reply.  Forgive me for asking, but what made you decide to start a completely new project instead of adding features to Puppetboard?  I'm currently discussing becoming a core contributor to Puppetboard since I feel it is a very nice base to build from.  I'm personally much more fond of Flask over Django, but of course this is subjective.

Just curious to understand your motivation for starting a new dashboard project :smile:

**Comment by propyless** [comment]
Well I needed a home project. Puppetboard is alright and all but its freakishly slow when you have over 2000 nodes. All the pages take a long time to load. Panopuppet has been tested with a puppetenv with over 36k nodes and still loads in a acceptable amount of time, < 5 seconds (on all pages regardless).
I wrote it using django because I've already written api's and stuff with flask and I wanted to try something else.
Python3 over python2 because people need to start using it.

**Comment by fgimian** [comment]
Thanks a lot for your reply.  I'm looking at implementing concurrent requests to PuppetDB for Puppetboard via Gevent so that should speed it up.  Though I must admit, we don't have anywhere near that scale so I wouldn't be able to really benchmark it, perhaps you can give it another try if I manage to add that in Puppetboard? :smile: 

Personally, I'm running both Puppetboard and PanoPuppet on my dev server at work and have it hooked up to the PuppetDB instances of all environments.  I really like both systems, and some of the features I have in mind for Puppetboard originate from your implementation.  It's great to get inspiration from one another :smile: 

Have a great night
Fotis

**Comment by propyless** [comment]
gevent will probably speed it up quite a bit i assume =). I need something like that as well tbh, i've been looking into nodejs for something similar. I don't have a 36k nodes(i wish) someone using panopuppet has 36k nodes.

I have thought about contributing to puppetboard, but the time it would have taken me to really get into the code, I would've already been done with panopuppet by that time!
I'm glad you like panopuppet! I hope I can keep the progress up so I don't fall behind puppetboard ;)
Thanks for your input once again, I hope we can continue helping one another!

**Comment by propyless** [comment]
@fgimian which parts of panopuppet do you like? is there anything you would like to add?
I've taken inspiration from both puppetboard and puppetexplorer so my features derive slightly from both.
