### ISSUE TITLE
Save Queries?

### ISSUE THREAD

**Issue by yotaka** [propyless/panopuppet#38]
I'd really like to save queries from the query builder.

And maybe show the results on the dashboard.

Like "All nodes of client company1" or "All nodes of accounting department systems". 

A first step might be to make queries GET-able so I can bookmark them. But dashboard integration would be nice.

**Comment by propyless** [comment]
Hello yotaka! This is already in the roadmap for panopuppet :)

**Comment by propyless** [comment]
#58
