### ISSUE TITLE
Provide some way to contact you for questions not worthy opening an issue

### ISSUE THREAD

**Issue by yotaka** [propyless/panopuppet#40]
I have so many questions about Panopuppet, but I don't want to open an issue for every question.

I see issues more like defects in the software, not for cases when I simply have a question.

Like: 
- How to update an existing installation? Will git-pull be sufficient?
- Sometimes xyz doesn't work. Is there an easy way to fix it?
- When will queries be saveable? (It's on the roadmap)
- Can I somehow make a button that opens panopuppet to show the result of a given query?

The thing is, there is no other way of contacting you (or someone who may answer questions).

GitHub doesn't come with a option to send direct messages. To contact a user on github, the user can provide a mail address. Also, many projects have an IRC channel (or jabber, or twitter, or younameit).

Could you please provide another way to contact you than opening issues?

**Comment by propyless** [comment]
Hello,
You can contact me on IRC Server Freenode, my nickname is Propyless there.

We can speak there about the stuff you want to ask me.

**Comment by propyless** [comment]
Saveable Queries will probably come some time after the QueryBuilder is working the way I want it.
When the api is done and the pages use ajax to show data.

**Comment by propyless** [comment]
There is an "upgrade" section in the README.md which explains how you can update panopuppet.

usually its as easy 123
git pull
<virtualenv activated> python manage.py collectstatic
service httpd/apache restart

**Comment by propyless** [comment]
saw your privmsg on freenode but you were offline by the time i was back
