### ISSUE TITLE
Dashboard -> Recent not showing Success Noop Failures

### ISSUE THREAD

**Issue by centric-jim** [propyless/panopuppet#45]
I'm not sure if this is a bug or if values just need to get recorded over time in the db.sqlite3 file.  

Anyway, in the Dashobard view choosing the Recent tab all values are 0 for Success Noop Failures or Skipped.  If I choose Change or Failed tabs I do get results (though they don't look correct - -I need to verify that). 

The same is true for selecting the Nodes view all values are 0.

If I select a node I do see a history of all reports.

Thanks and sorry if this is not a bug

**Comment by propyless** [comment]
Hi there centric-jim! 

Hm I am not entirely sure about what you mean.. The recents tab only shows the 25 latest reports available regardless of whether they are failed, changed or unchanged.

Do you mind me asking for a screenshot or two showing the issue you are experiencing?

**Comment by propyless** [comment]
Are you satisfied with the answer i gave you?

Can i close the issue?
