### ISSUE TITLE
Node Reports Page - start and end times are the same

### ISSUE THREAD

**Issue by exodusftw** [propyless/panopuppet#50]
The reports page for each node appears to accurately chart the runtime of each puppet run, but the reports section for each node appears to show the start and end time as the exact same time.

**Comment by propyless** [comment]
Im guessing this issue affects the reports_page Branch?
I've found the issue and it should be fixed now
https://github.com/propyless/panopuppet/commit/de70686d1d10c51f703bcda6f69df91dbdcc26a9
