### ISSUE TITLE
Feature: Save queries and filters

### ISSUE THREAD

**Issue by propyless** [propyless/panopuppet#58]
Add the ability to save, select and use the queries created via the querybuilder.

**Comment by propyless** [comment]
#57 
after the issue above it closed i will start with this.

**Comment by propyless** [comment]
@yotaka soon it will be completed, just some testing and a function to delete queries needs to be implemented.
Take a look at PR #60

**Comment by yotaka** [comment]
Hi Propyless,

I currently don't have a running puppet infrastructure. As an IT
consultant, I look forward to another project using puppet, but until then,
I cannot practically use panopuppet.

I will write back if this changes.

Regards,

yotaka

**Comment by propyless** [comment]
Ah Ok! Thats a shame, does the company you set up panopuppet for know how
to upgrade and update panopuppet?

BR,
Takeshi

**Comment by yotaka** [comment]
I build a prototype for using puppet in their environment for them. They
will now evaluate some other open points, do some preparation (mainly
packaging their software) and then will either decide for or against using
puppet. They have seen panopuppet in the prototype, it meet their
requirements and I think when they decide for using puppet they will also
decide for panopuppet again.

**Comment by propyless** [comment]
OK!

**Comment by propyless** [comment]
Merged
