### ISSUE TITLE
PuppetDB 3.0 Support

### ISSUE THREAD

**Issue by propyless** [propyless/panopuppet#61]
Hi!

This is a ticket which i'm hoping I can get some response for.

How many of you are already using PDB3.0 and how many need the support for PDB3.0 in PanoPuppet already today?

This is so I can estimate the time I need to get it working for PDB3.0 (and setup a PDB3.0 test environment)

//Takeshi

**Comment by johnzimm** [comment]
I've been using PuppetBoard and PuppetExplorer and recently upgraded to PuppetDB 3.0.  I was checking on your project to see if you had support for PuppetDB 3.x / API v4 yet.  If there was support for it I would use it today :-)

**Comment by propyless** [comment]
Alright, just give me some time to set up a puppetdb3 environment so i have something to dev with

**Comment by propyless** [comment]
quite a lot of changes done to the reports/events api's, might take a well to sort out.

**Comment by propyless** [comment]
Hi Johnzimm,

I've created a new release which works with Puppetdb 3.0 now. (v1.0.0)
There may be bugs since I don't have a proper PuppetDB 3.0 environment to test with so just create a ticket and i'll try to reproduce and fix it..

**Comment by propyless** [comment]
Reason I ended puppetdb 2.x support is because that PuppetLabs themselves has removed the puppetdb api's v2, and v3. So therefore I don't see why PanoPuppet should support lower versions than the current v4.
